version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: diego020304
      POSTGRES_DB: gerenciador_tarefas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crud-tarefas:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://diego:diego020304@postgres:5432/gerenciador_tarefas
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data:
